# Generated by Django 5.0.6 on 2024-08-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.RenameField("Genre", "genre", "name"),
    ]
