# Generated by Django 5.0.6 on 2024-08-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20240818_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, choices=[('DIR', 'Director'), ('ACT', 'Actor')], max_length=30, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('ANM', 'Animated'), ('BIO', 'Biography'), ('COM', 'Comedy'), ('CRM', 'Crime'), ('DET', 'Detective'), ('DOC', 'Documentary'), ('DRM', 'Drama'), ('EPC', 'Epic'), ('FAM', 'Family'), ('FAN', 'Fantasy'), ('FN', 'Film-Hoir'), ('HIS', 'History'), ('HOR', 'Horror'), ('MUS', 'Musical'), ('MYS', 'Mystery'), ('ROM', 'Romance'), ('SF', 'Sci-Fi'), ('SPT', 'Sport'), ('TLR', 'Thriller'), ('WAR', 'War'), ('WST', 'Western')], max_length=30),
        ),
        migrations.AddField(
            model_name='film',
            name='cast_crew',
            field=models.ManyToManyField(blank=True, to='films.castcrew'),
        ),
    ]
