# Generated by Django 5.0.6 on 2024-08-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_rename_profession_castcrew_professions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cover',
            field=models.ImageField(blank=True, null=True),
        ),
    ]
